name: Build THT Release

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-build.yml'
      - '.cache-buster'
      - 'Dockerfile'
      - 'bin/**'
      - 'zsh/**'

jobs:
  build:
    name: Build THT release
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
    # - 
    #   name: Set up QEMU # used for arm64 builds
    #   uses: docker/setup-qemu-action@v1
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1      
    -
      name: Login to DockerHub
      uses: docker/login-action@v1.10.0 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    -
      name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx
    - 
      name: Build and push
      uses: docker/build-push-action@v2.6.1
      with:
        platforms: linux/amd64 #,linux/arm64,linux/arm/v7
        tags: |
          ethack/tht:latest
          ethack/tht:${{ github.sha }}
          ghcr.io/ethack/tht:latest
          ghcr.io/ethack/tht:${{ github.sha }}
        build-args: |
          MAXMIND_LICENSE=${{ secrets.MAXMIND_LICENSE }}
          THT_HASH=${{ github.sha }}
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

  test:
    name: Run BATS tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - 
      name: BATS 
      env:
        # Use Github Container Registry for faster downloads (hopefully)
        IMAGE: ghcr.io/ethack/tht:latest
      run: |
        ./tht --dev run "/usr/local/test/bats/bin/bats /usr/local/test"